
export const USER_LOGGED_IN = 'USER_LOGGED_IN'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'


export const INVALIDATE_DEVICES_DATA = 'INVALIDATE_DEVICES_DATA'

export const REQUEST_DEVICES = 'REQUEST_DEVICES'
export const RECEIVE_DEVICES = 'RECEIVE_DEVICES'
export const RECEIVE_DEVICES_FAILED = 'RECEIVE_DEVICES_FAILED'

export const TOGGLE_DEVICE_PANE = 'TOGGLE_DEVICE_PANE'

export const REQUEST_APPLICATIONS = 'REQUEST_APPLICATIONS'
export const RECEIVE_APPLICATIONS = 'RECEIVE_APPLICATIONS'
export const RECEIVE_APPLICATIONS_FAILED = 'RECEIVE_APPLICATIONS_FAILED'

export const UPDATE_MAP_POSITION = 'UPDATE_MAP_POSITION'

export const mapConstants = {
  REQUEST_MAP_GATEWAYS: 'REQUEST_MAP_GATEWAYS',
  RECEIVE_MAP_GATEWAYS: 'RECEIVE_MAP_GATEWAYS',
  RECEIVE_MAP_GATEWAYS_FAILED: 'RECEIVE_MAP_GATEWAYS_FAILED',

  RECEIVE_GATEWAY_DETAILS: 'RECEIVE_GATEWAY_DETAILS',

  REQUEST_MAP_GW_CIRCLES: 'REQUEST_MAP_GW_CIRCLES',
  RECEIVE_MAP_GW_CIRCLES: 'RECEIVE_MAP_GW_CIRCLES',
  RECEIVE_MAP_GW_CIRCLES_FAILED: 'RECEIVE_MAP_GW_CIRCLES_FAILED'
}
